name: Build APK

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Подтягиваем репозиторий вместе с submodules
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # 2️⃣ Устанавливаем JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Устанавливаем Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    # 4️⃣ Сборка debug APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # 5️⃣ Загружаем APK как артефакт
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
